version: '3.8'

services:
  urlshortener_db:
    container_name: urlshortener_db
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=urls
    restart: always
    volumes:
      - ./data:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    env_file:
      - .env.local
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - urlshortener_db
